# Site settings
title: Mindful Leadership for Highly Technical Organizations
email: wyld3rbit@users.noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
  Explore the transformative journey of mastering engineering leadership through groundbreaking innovation, impactful management, and fostering meaningful human connections. Delve into the insights and experiences of a seasoned software engineering leader, navigating the challenges and triumphs in senior management roles across diverse industries.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://wyld3rbit.github.io" # the base hostname & protocol for your site
twitter_username: wyld3rbit
github_username: wyld3rbit
linkedin_username: arkapattanayak

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
theme: jekyll-theme-hacker

plugins:
  - octopress-date-format
  - jekyll-feed
  - jekyll-gist
