# Site settings
title: Mindful Leadership for Highly Technical Organizations
email: wyld3rbit@users.noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
A strategic software engineering leader with a proven track record in driving innovation through privacy-first, user-centered product development. Expertise spans technical leadership, team management, and delivering high-impact solutions that balance cutting-edge technology with ethical responsibility. Currently pivoting toward computational intelligence, particularly in generative AI and computer vision, with a focus on leading transformative initiatives that push the boundaries of what's possible while ensuring technology serves society’s best interests. Seeking a senior leadership role to leverage these skills, shaping the direction of both people and technology, and delivering impactful, scalable solutions to complex challenges.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://wyld3rbit.github.io" # the base hostname & protocol for your site
twitter_username: wyld3rbit
github_username: wyld3rbit
linkedin_username: arkapattanayak

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
theme: jekyll-theme-hacker

plugins:
  - octopress-date-format
  - jekyll-feed
  - jekyll-gist
